@library("belajar-jenkins-shared-library@main")_

import belajar.jenkins.Output;

pipeline{
    agent any
    stages {
        stage("Hello Groovy"){
            steps{
                script{
                    Output.hello("Groovy")
                }
            }
        }
    }
}